# Generated by Django 4.1 on 2022-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pictures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_category",
                    models.CharField(
                        choices=[
                            ("images/city", "City"),
                            ("images/nature", "Nature"),
                            ("image/panorama", "Panorama"),
                            ("image/long_exposure", "Long Exposure"),
                        ],
                        max_length=19,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=models.CharField(
                            choices=[
                                ("images/city", "City"),
                                ("images/nature", "Nature"),
                                ("image/panorama", "Panorama"),
                                ("image/long_exposure", "Long Exposure"),
                            ],
                            max_length=19,
                        )
                    ),
                ),
            ],
        ),
    ]
