# Generated by Django 4.1 on 2022-11-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Pictures", new_name="Portfolio_Pictures",),
    ]
