# Generated by Django 4.1 on 2022-11-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_pictures_portfolio_pictures"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Portfolio_Pictures", new_name="Portfolio_Picture",
        ),
    ]
