# Generated by Django 4.1 on 2022-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_portfolio_pictures_portfolio_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio_picture",
            name="image",
            field=models.ImageField(
                upload_to=[
                    ("images/city", "City"),
                    ("images/nature", "Nature"),
                    ("image/panorama", "Panorama"),
                    ("image/long_exposure", "Long Exposure"),
                ]
            ),
        ),
    ]
