# Generated by Django 4.1 on 2022-12-01 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_portfolio_picture_image_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio_picture",
            name="image_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfolio_picture",
            name="image",
            field=models.ImageField(unique=True, upload_to="images"),
        ),
    ]
